### ISSUE TITLE
No such file or directory: 'output.txt

### ISSUE THREAD

**Issue by jsgounot** [kangxiongbin/StrainXpress#1]
Hi,

I've tried your software and my run ends up with an error

``` bash
$ python ~/strainxpress/StrainXpress/scripts/strainxpress.py -fq input/ecoli.interleaved.fastq.gz -t 8 -insert_size 300 -average_read_len 150
successfully execute: split input/ecoli.interleaved.fastq.gz -l 252552 -d -a 2 sub
successfully execute: cat cmd_overlap.sh | xargs -i -P 8 bash -c "{}";
successfully execute: for X in sub*.map; do sort  -k3 -nr < $X > sorted-$X; done;
successfully execute: sort -k3 -nr -m sorted-sub*.map > all_reads_sort.map;
successfully execute: rm *sub*;
Traceback (most recent call last):
  File "/home/ubuntu/strainxpress/StrainXpress/scripts/strainxpress.py", line 171, in <module>
    sys.exit(main())
  File "/home/ubuntu/strainxpress/StrainXpress/scripts/strainxpress.py", line 66, in main
    execute(cmd_fq_name)
  File "/home/ubuntu/strainxpress/StrainXpress/scripts/strainxpress.py", line 161, in execute
    with open("output.txt","r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'output.txt
```

**Comment by kangxiongbin** [comment]
> 

Hi,
Now, Strainxpress cannot process compress fq file, later I'll update it. Can you uncompress your fq file and then try again?

**Comment by jsgounot** [comment]
Hi. Indeed, it worked with uncompressed fq file. Thanks.
